# Generated by Django 4.2 on 2023-05-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_form_checkbox_alter_form_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='checkbox',
        ),
        migrations.AddField(
            model_name='form',
            name='exampaper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='textbook',
            field=models.BooleanField(default=False),
        ),
    ]
