# Generated by Django 4.2 on 2023-05-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_form_checkbox_form_exampaper_form_textbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.TextField(max_length=100),
        ),
    ]
